/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/earth.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials['Earth Material']} geometry={nodes.Sphere.geometry} scale={[1, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/earth.glb')
